ignore-bounds-checks: true

matrix-specs:
  "ws2812b:32x8":
    power_limit_amps: 2.5
    width-height: [8, 32]

matrices:
  mat1:
    spec: "ws2812b:32x8"
    pos: [0, 0]
    rot: up
  mat2:
    spec: "ws2812b:32x8"
    pos: [8, 0]
    rot: up
  mat3:
    spec: "ws2812b:32x8"
    pos: [16, 0]
    rot: up
  mat4:
    spec: "ws2812b:32x8"
    pos: [24, 0]
    rot: up
  mat5:
    spec: "ws2812b:32x8"
    pos: [32, 0]
    rot: up
  mat6:
    spec: "ws2812b:32x8"
    pos: [40, 0]
    rot: up

clients:
  24-0A-C4-0D-AA-F8:
    matrix-connections:
      - pin: 13
        matrices: [mat1]
  24-0A-C4-0D-76-10:
    matrix-connections:
      - pin: 13
        matrices: [mat2]
  30-C6-F7-26-05-D4:
    matrix-connections:
      - pin: 16
        matrices: [mat3]
      - pin: 17
        matrices: [mat4]
      - pin: 18
        matrices: [mat5]
      - pin: 19
        matrices: [mat6]
